### ISSUE TITLE
ImportError: No module named 'framebuf'

### ISSUE THREAD

**Issue by easleyjs** [adafruit/Adafruit_CircuitPython_MAX7219#16]
Got the adafruit_max7219 module installed on my RPi, but when I try to run the 8x8 example code, I'm getting the follow error:

---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-4adaaf47f473> in <module>()
----> 1 from adafruit_max7219 import matrices

/home/pi/.local/lib/python3.5/site-packages/adafruit_max7219/matrices.py in <module>()
     27 """
     28 from micropython import const
---> 29 from adafruit_max7219 import max7219
     30 
     31 __version__ = "0.0.0-auto.0"

/home/pi/.local/lib/python3.5/site-packages/adafruit_max7219/max7219.py in <module>()
     58 from adafruit_bus_device import spi_device
     59 from micropython import const
---> 60 import framebuf
     61 
     62 __version__ = "0.0.0-auto.0"

ImportError: No module named 'framebuf'

**Comment by Tasm-Devil** [comment]
I get the same Error with the current version of Circuitpython 4 beta on a nrf52840 Express
No module named 'framebuf'

Is this the reason: [https://github.com/adafruit/circuitpython/pull/1427](https://github.com/adafruit/circuitpython/pull/1427)

**Comment by ladyada** [comment]
thats right, we removed it - this library will need to be updated to use `adafruit_framebuf` (which is very similar)
https://github.com/adafruit/Adafruit_CircuitPython_framebuf
@Tasm-Devil wanna take a crack at it :)

**Comment by Tasm-Devil** [comment]
ok. 
...
It's done. -> https://github.com/adafruit/Adafruit_CircuitPython_MAX7219/pull/17/commits
