### ISSUE TITLE
using example, AttributeError: 'module' object has no attribute 'Matrix8x8'

### ISSUE THREAD

**Issue by titimoby** [adafruit/Adafruit_CircuitPython_MAX7219#28]
I tried both with the .mpy files from Adafruit libraries bundle and from this repository code.
When I try the example on my feather M4 express, I have an issue with matrices module.
```
>>> from adafruit_max7219 import matrices
>>> import board
>>> import busio
>>> import digitalio
>>> import time
>>> cs = digitalio.DigitalInOut(board.A2)
>>> clk = board.SCK
>>> din = board.MOSI
>>> spi = busio.SPI(clk, MOSI=din)
>>> display = matrices.Matrix8x8(spi, cs)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'Matrix8x8'
```
Did I miss something?

Edit: I forgot to mention I was using CircuitPython 6.0.0
I'll try to flash latest stable 5.3 available in S3 (5.3.0 I think)

**Comment by ladyada** [comment]
hmm @deshipu dya know what it could be? the spelling looks right?

**Comment by titimoby** [comment]
I've done it with copy paste from the readme if this can help.

**Comment by titimoby** [comment]
As I mentionner I my edit, I tried with CircuitPython 5.3.0 and I did not had the issue.
This seems to be something related to 6.0.0

**Comment by deshipu** [comment]
Sorry, I didn't see this. If I had to guess, I would say it's  corrupted file...

**Comment by titimoby** [comment]
I still have the parts involved. I can try once more with various CP versions if it helps.

**Comment by titimoby** [comment]
Adafruit CircuitPython 6.3.0 on 2021-06-01; Adafruit Feather M4 Express with samd51j19
adafruit_max 7219 from adafruit-circuitpython-bundle-6.x-mpy-20210204

and still the same error.
I can add that:
```
>>> dir(matrices)
['__class__', '__file__', '__name__', 'const']
```

**Comment by titimoby** [comment]
Adafruit CircuitPython 7.0.0 on 2021-09-20; Adafruit Feather M4 Express with samd51j19
with libraries from adafruit-circuitpython-bundle-7.x-mpy-20211003

it works. 

So I flashed back to:
Adafruit CircuitPython 6.3.0 on 2021-06-01; Adafruit Feather M4 Express with samd51j19
with libraries from latest 6.x : adafruit-circuitpython-bundle-6.x-mpy-20211003

and... it also works.
I don't know where things went corrupted on my board, but problem solved as far I can see.

Thanks a lot.
